#!/usr/bin/env bash

if
  [[ -s "GEM_HOME/environment" ]]
then
  source "GEM_HOME/environment"
  exec elastic_ruby_console "$@"
else
  echo "ERROR: Missing RVM environment file: 'GEM_HOME/environment'" >&2
  exit 1
fi
